name: dotnet publish

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.100' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Publish
        run:  |
              dotnet publish -r win-x64 --self-contained false -o bin/win-x64/
              dotnet publish -r linux-x64 --self-contained false -o bin/linux-x64/
              dotnet publish -r linux-musl-x64 --self-contained false -o bin/linux-musl-x64/
              mv bin/win-x64/Reecon.exe bin/Reecon-windows.exe
              mv bin/linux-x64/Reecon bin/reecon-linux-x64
              mv bin/linux-musl-x64/Reecon bin/reecon-linux-musl-x64
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest Development Build"
          files: |
                bin/Reecon-windows.exe
                bin/Reecon-linux-x64
                bin/Reecon-linux-musl-x64
